## Reference: https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml

# MD013/line-length - Line length
MD013:
  line_length: 100
  stern: true
  # to match the .flake8 config for Python
  code_block_line_length: 120

# MD024/no-duplicate-heading/no-duplicate-header - Multiple headings with the same content
MD024:
  # Only check sibling headings
  allow_different_nesting: true
  # Only check sibling headings
  # siblings_only: false

# MD033/no-inline-html - Inline HTML
MD033:
  # Allowed elements
  allowed_elements: [img]
